// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZXsZ0eLQDAyymi1S8jcwG55qYUY_t1Q0',
    appId: '1:936482920345:web:65efc2c49c565ef0066508',
    messagingSenderId: '936482920345',
    projectId: 'events-4ff3e',
    authDomain: 'events-4ff3e.firebaseapp.com',
    storageBucket: 'events-4ff3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIoa0N1X0snuo7f9vzqjI0XX9o9Cw839E',
    appId: '1:936482920345:android:fe484f151a290433066508',
    messagingSenderId: '936482920345',
    projectId: 'events-4ff3e',
    storageBucket: 'events-4ff3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVOX3ynwz09SZSbQI290X3CJL98AZlmr0',
    appId: '1:936482920345:ios:a30357f3248cc9e2066508',
    messagingSenderId: '936482920345',
    projectId: 'events-4ff3e',
    storageBucket: 'events-4ff3e.appspot.com',
    iosClientId: '936482920345-6cb53svgs952o35fedqs3s61b0bra7h6.apps.googleusercontent.com',
    iosBundleId: 'com.example.events',
  );
}
